### ISSUE TITLE
the edit cursor is in the wrong position

### ISSUE THREAD

**Issue by dattran1232003** [uiwjs/react-md-editor#134]
After I change font family (in somewhere I don't remember), I got this UI's error:
![Screen Shot 2021-04-04 at 1 32 03 PM](https://user-images.githubusercontent.com/57513789/113500707-66380d00-954a-11eb-841e-6819be05afe1.png)

It only happens on the title (and other lines has special characters in begin of line), on normal lines it's doesn't happen. the edit cursor does not move to the end of the line, no matter whether I press the end of a line or use the arrow keys, it is there.

I'm found a way to fix, add some css (scss in my case) to change font family of "**span.token.title.important**" and "**span.token.title.important .token.punctuation**" like this:
```scss
// scss
span.token.title.important {
  font-family: inherit;
  .token.punctuation {
    font-family: inherit;
  }
}

// css
span.token.title.important {
      font-family: inherit;
}
  span.token.title.important .token.punctuation {
    font-family: inherit;
  }
```

"**span.token.title.important**" and "**.token.punctuation**" took **font-family** css from its parent and problem has been fix:
![Screen Shot 2021-04-04 at 1 58 32 PM](https://user-images.githubusercontent.com/57513789/113501276-07749280-954e-11eb-8ab3-d44215509dfe.png)
