### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by alfuhigi** [uiwjs/react-md-editor#183]
is there any way to use react-md-editor in RTL language,
 
![Image of  issue ](https://i.ibb.co/G3pc4L2/rtlsupport.png)

**Comment by jaywcjlove** [comment]
@alfuhigi I don't quite understand the RTL language. How to show it?

**Comment by alfuhigi** [comment]
sorry, I was mean RTL speaking language like Arabic, Urdu, that can read right to left 
in my App I use CSS direction to RTL to set all element in  to be in RTL direction 
so as you saw in image the source and preview go to right side it is better 
```
<div  className={{direction:"rtl"}}>
 <MDEditor
        value={value}
        onChange={setValue}
      />
</div>
```

**Comment by jaywcjlove** [comment]
@alfuhigi  https://codesandbox.io/s/rtl-support-markdown-editor-for-react-forked-1p29e?file=/index.css

```css
.w-md-editor-toolbar {
  direction: rtl;
}
.w-md-editor-text-input,
.w-md-editor-text-pre,
.w-md-editor-preview {
  direction: rtl;
  text-align: right;
}
```
