### ISSUE TITLE
Customize icon size

### ISSUE THREAD

**Issue by jeepers3327** [uiwjs/react-md-editor#387]
Hi, 

I would like to ask if there's a way to customize the icon size for each existing commands. I check the source code and all the icons width and height are set to `12` which is pretty small.

Can we override the icon of the existing command because if there's none maybe I can just copy the whole existing commands but changed the dimension of the svg icon

**Comment by jaywcjlove** [comment]
There is no good way to define icon size.
Because there needs to be an easier way to define toolbars. Unless we redesign the toolbar definition API.

Similar to the API design below:

```jsx
<MDEditor.Markdown 
  source="...."
  commands={
    <Command>
      <Title3 />
      <CommandGroup>
        <Title1 />
        <Title2 />
        <Title3 width="12" height="12" buttonProps={{ 'aria-label': 'Insert title'}} />
      </CommandGroup>
    </Command>
  }
/>
```

This one has more work and can be considered for expansion in the next version. The only solution so far is as follows:

```tsx
const title1: ICommand = {
  ...commands.title1,
  icon: (
    <svg width="23" height="23" viewBox="0 0 520 520">
      <path fill="currentColor" d="M15.708333..." />
    </svg>
  ),
};
```

@jeepers3327

**Comment by jeepers3327** [comment]
@jaywcjlove  I'll try what you suggested. Thanks

**Comment by tavik000** [comment]
```css
.w-md-editor-toolbar {
  height: 50px !important;
}

.w-md-editor-toolbar li>button {
  width: 40px !important;
  height: 40px !important;
  margin-left: 10px !important;
  margin-right: 10px !important;
}

.w-md-editor-toolbar li>button>svg {
  width: 20px !important;
  height: 20px !important;
  align-content: center !important;
  vertical-align: middle !important;
  display: inherit !important;
}
```


overwrite with this CSS in `global.css`
feel free to customize.

it will become larger like this. 
![image](https://github.com/user-attachments/assets/f12efaa7-bcf6-4a50-804c-c4a6b399ed4b)
