### ISSUE TITLE
How do I remove the border?

### ISSUE THREAD

**Issue by jongjin1010** [uiwjs/react-md-editor#453]
jsx (React)
```jsx
<S.Markdown>
  <MDEditor hideToolbar={true} onChange={setContent} value={content} />
</S.Markdown>
```

css (Emotion)
```css
export const Markdown = styled.div`
  width: 100%;
  border: none;
  padding: 20px;

  .wmde-markdown-var.w-md-editor.w-md-editor-show-live {
    min-height: 40vh !important;
    height: fit-content !important;
    background-color: #1f2125;
  }

  .w-md-editor-input {
    width: 100%;
    color: white;
    background-color: #1f2125;
  }

  .w-md-editor-text-input {
    height: 100%;
  }

  .w-md-editor-text-pre,
  .w-md-editor-text-input {
    height: 40vh;
    border: none;
  }

  .w-md-editor-preview {
    display: none;
  }
`;

```

view

<img width="1248" alt="스크린샷 2022-11-07 오후 6 06 06" src="https://user-images.githubusercontent.com/81551906/200270582-ae87a6a8-47cf-479c-95c6-4dc59c4291d4.png">

**Comment by jaywcjlove** [comment]
@jongjin1010 Need an  props API?

```css
.w-md-editor {
  box-shadow: inherit !important;
}
```
