### ISSUE TITLE
[BUG] :focus css selector has no effect

### ISSUE THREAD

**Issue by TimAufdemKampe** [uiwjs/react-md-editor#513]
:focus css selector has no effect on the editor textarea.

If the textarea is ":active" the background color is red but if the textarea is ":focus" it's not yellow.

Standbox Example: https://codesandbox.io/embed/react-md-editor-custom-toolbars-forked-g9rs2o?fontsize=14&hidenavigation=1&theme=dark

**Comment by jaywcjlove** [comment]
@TimAufdemKampe https://codesandbox.io/embed/react-md-editor-custom-toolbars-forked-dg5q5l?fontsize=14&hidenavigation=1&theme=dark

```css
.w-md-editor-text-input:focus,
.w-md-editor-text-input:focus-visible {
  background-color: yellow !important;
  -webkit-text-fill-color: #f70000;
  outline: 2px solid red;
}

.w-md-editor-text-input:active {
  background-color: red;
}

```
