### ISSUE TITLE
Using taliwind css to change the font?

### ISSUE THREAD

**Issue by jimkk159** [uiwjs/react-md-editor#526]
Hello，
I know I can use the class name to  change the editor style

```JavaScript
.w-md-editor-text-pre > code,
.w-md-editor-text-input {
  font-size: 23px !important;
  line-height: 24px !important;
}
```
I want to use taliwind css to change the default editor font style,
However, the added font-family seems like does not work (replace by the default font-family)

```JavaScript
.my-taliwind-css-family {
    font-family: some style
}
```
replace by

```JavaScript
.wmde-markdown {
    -webkit-text-size-adjust: 100%;
    font-family: -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji';
    font-size: 16px;
    line-height: 1.5;
    word-wrap: break-word;
    color: var(--color-fg-default);
    background-color: var(--color-canvas-default);
}

```

Is there any good solution to deal with this?

**Comment by jaywcjlove** [comment]
@jimkk159 

```css
.w-md-editor-text-input,
.w-md-editor-text-pre > code,
.w-md-editor-text-pre 
{
  font-family: Arial,sans-serif !important;
}
```

**Comment by jaywcjlove** [comment]
Upgrade `v3.23.0`

```css
.w-md-editor {
  --md-editor-font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif !important;
}
```
