### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by aleksandrmakarov-dev** [uiwjs/react-md-editor#566]
I'm developing app with Next.js and want to make font size inside markdown editor bigger. I added styles to `globals.css`
```
.w-md-editor-text-pre > code,
.w-md-editor-text-input {
  font-size: 2rem !important;
  line-height: 2.5rem !important;
}
```
Imported `globals.css` to page where I have MDEditor  
And I have an issue, the size of font doesn't change although, if I select text, selected text is the size I set in styles  
![image](https://github.com/uiwjs/react-md-editor/assets/128474912/c48eb034-5ef3-4e20-b25c-12cb91b0b176)  
In browser's console I can see that styles are applied  
![image](https://github.com/uiwjs/react-md-editor/assets/128474912/74eb001d-6b71-4332-afea-37ef55bcc243)

**Comment by jaywcjlove** [comment]
@aleksandrmakarov-dev 

```css
.w-md-editor-text-input,
.w-md-editor-text-pre > code,
.w-md-editor-text-pre {
  font-size: 2rem !important;
  line-height: 2.5rem !important;
}
```
