### ISSUE TITLE
[BUG] numbered list can't render number in preview panel

### ISSUE THREAD

**Issue by zshnb** [uiwjs/react-md-editor#627]
<img width="811" alt="image" src="https://github.com/uiwjs/react-md-editor/assets/17894980/f019ea6c-41cc-4aa8-873b-d1500c24fc66">

as you can see in the pic, left I write numbered list like
1. 1
2. 2
3. 3

but right doesn't render number.
how can I fix this?

**Comment by h4ck4life** [comment]
I am having the same issue

**Comment by h4ck4life** [comment]
@zshnb try add below css to override it,

```css
.wmde-markdown ol {
  list-style: auto !important;
}
```

You should now see the numbering.

**Comment by jaywcjlove** [comment]
<img width="908" alt="image" src="https://github.com/uiwjs/react-md-editor/assets/1680273/02ddd546-4074-442c-87d8-c83626b3e16f">

@h4ck4life @zshnb  Is it because the default styles have been reset? Do I need to add the default styles to the CSS?

**Comment by leonardosarmentocastro** [comment]
same here:

![Screenshot 2024-10-09 at 08 18 12](https://github.com/user-attachments/assets/6e73db91-d03f-42ec-9558-4f0e04fdb98d)


@h4ck4life suggestion worked for me:

```css
.wmde-markdown ol { list-style: auto !important; }
.wmde-markdown ul { list-style: disc !important; }
```

![Screenshot 2024-10-09 at 08 20 42](https://github.com/user-attachments/assets/a14a7008-fb0b-4864-8f37-b9b96652c7d5)

thanks!

**Comment by JacobPatrick** [comment]
@h4ck4life suggestion worked for me but only with unordered list

<img width="1216" alt="Image" src="https://github.com/user-attachments/assets/355787ae-c65f-42cc-ad70-ace67ca6efe7" />

```css
.wmde-markdown ol { list-style: decimal !important; }
.wmde-markdown ul { list-style: disc !important; }
```

in fact whatever I put in `ol {...}` the bullet kept invisible
