### ISSUE TITLE
css variables 藏在哪里了找不到

### ISSUE THREAD

**Issue by 18601673727** [uiwjs/react-md-editor#633]
想修改这个变量的值`--color-accent-fg`但是翻遍了找不到是哪里定义出来的捏

**Comment by 18601673727** [comment]
原来在这里https://github.com/uiwjs/react-markdown-preview/blob/709a50e3139465c4353349e57ccf63ef7de1b102/core/src/styles/markdown.less#L43...

通过
```css
* {
  --color-accent-fg: [myNewValue];
}
```
粗暴的解决了...
